package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeliverytype<M extends BaseDeliverytype<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public void setContinueWeight(java.lang.Double continueWeight) {
		set("continueWeight", continueWeight);
	}

	public java.lang.Double getContinueWeight() {
		return get("continueWeight");
	}

	public void setContinueWeightPrice(java.math.BigDecimal continueWeightPrice) {
		set("continueWeightPrice", continueWeightPrice);
	}

	public java.math.BigDecimal getContinueWeightPrice() {
		return get("continueWeightPrice");
	}

	public void setContinueWeightUnit(java.lang.Integer continueWeightUnit) {
		set("continueWeightUnit", continueWeightUnit);
	}

	public java.lang.Integer getContinueWeightUnit() {
		return get("continueWeightUnit");
	}

	public void setDeliveryMethod(java.lang.Integer deliveryMethod) {
		set("deliveryMethod", deliveryMethod);
	}

	public java.lang.Integer getDeliveryMethod() {
		return get("deliveryMethod");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setFirstWeight(java.lang.Double firstWeight) {
		set("firstWeight", firstWeight);
	}

	public java.lang.Double getFirstWeight() {
		return get("firstWeight");
	}

	public void setFirstWeightPrice(java.math.BigDecimal firstWeightPrice) {
		set("firstWeightPrice", firstWeightPrice);
	}

	public java.math.BigDecimal getFirstWeightPrice() {
		return get("firstWeightPrice");
	}

	public void setFirstWeightUnit(java.lang.Integer firstWeightUnit) {
		set("firstWeightUnit", firstWeightUnit);
	}

	public java.lang.Integer getFirstWeightUnit() {
		return get("firstWeightUnit");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("orderList", orderList);
	}

	public java.lang.Integer getOrderList() {
		return get("orderList");
	}

	public void setDefaultdeliverycorpId(java.lang.String defaultdeliverycorpId) {
		set("defaultDeliveryCorp_id", defaultdeliverycorpId);
	}

	public java.lang.String getDefaultdeliverycorpId() {
		return get("defaultDeliveryCorp_id");
	}

}
