package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticlecategory<M extends BaseArticlecategory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public void setMetaDescription(java.lang.String metaDescription) {
		set("metaDescription", metaDescription);
	}

	public java.lang.String getMetaDescription() {
		return get("metaDescription");
	}

	public void setMetaKeywords(java.lang.String metaKeywords) {
		set("metaKeywords", metaKeywords);
	}

	public java.lang.String getMetaKeywords() {
		return get("metaKeywords");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("orderList", orderList);
	}

	public java.lang.Integer getOrderList() {
		return get("orderList");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}

	public java.lang.String getPath() {
		return get("path");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

}
