package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserID(java.lang.Integer userID) {
		set("userID", userID);
	}

	public java.lang.Integer getUserID() {
		return get("userID");
	}

	public void setModuleID(java.lang.Integer moduleID) {
		set("moduleID", moduleID);
	}

	public java.lang.Integer getModuleID() {
		return get("moduleID");
	}

	public void setPostCount(java.lang.Integer postCount) {
		set("postCount", postCount);
	}

	public java.lang.Integer getPostCount() {
		return get("postCount");
	}

	public void setReplyCount(java.lang.Integer replyCount) {
		set("replyCount", replyCount);
	}

	public java.lang.Integer getReplyCount() {
		return get("replyCount");
	}

	public void setPv(java.lang.Integer pv) {
		set("pv", pv);
	}

	public java.lang.Integer getPv() {
		return get("pv");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setEmotion(java.lang.Integer emotion) {
		set("emotion", emotion);
	}

	public java.lang.Integer getEmotion() {
		return get("emotion");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setIsNice(java.lang.Boolean isNice) {
		set("isNice", isNice);
	}

	public java.lang.Boolean getIsNice() {
		return get("isNice");
	}

	public void setIsUp(java.lang.Boolean isUp) {
		set("isUp", isUp);
	}

	public java.lang.Boolean getIsUp() {
		return get("isUp");
	}

}
