package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNavigation<M extends BaseNavigation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public void setIsBlankTarget(java.lang.Boolean isBlankTarget) {
		set("isBlankTarget", isBlankTarget);
	}

	public java.lang.Boolean getIsBlankTarget() {
		return get("isBlankTarget");
	}

	public void setIsVisible(java.lang.Boolean isVisible) {
		set("isVisible", isVisible);
	}

	public java.lang.Boolean getIsVisible() {
		return get("isVisible");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("orderList", orderList);
	}

	public java.lang.Integer getOrderList() {
		return get("orderList");
	}

	public void setPosition(java.lang.Integer position) {
		set("position", position);
	}

	public java.lang.Integer getPosition() {
		return get("position");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
