package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setSex(java.lang.Boolean sex) {
		set("sex", sex);
	}

	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("headImg", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("headImg");
	}

	public void setBlogUrl(java.lang.String blogUrl) {
		set("blogUrl", blogUrl);
	}

	public java.lang.String getBlogUrl() {
		return get("blogUrl");
	}

	public void setFeeling(java.lang.String feeling) {
		set("feeling", feeling);
	}

	public java.lang.String getFeeling() {
		return get("feeling");
	}

	public void setRegistDate(java.util.Date registDate) {
		set("registDate", registDate);
	}

	public java.util.Date getRegistDate() {
		return get("registDate");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

}
