package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setIsAccountEnabled(java.lang.Boolean isAccountEnabled) {
		set("isAccountEnabled", isAccountEnabled);
	}

	public java.lang.Boolean getIsAccountEnabled() {
		return get("isAccountEnabled");
	}

	public void setIsAccountExpired(java.lang.Boolean isAccountExpired) {
		set("isAccountExpired", isAccountExpired);
	}

	public java.lang.Boolean getIsAccountExpired() {
		return get("isAccountExpired");
	}

	public void setIsAccountLocked(java.lang.Boolean isAccountLocked) {
		set("isAccountLocked", isAccountLocked);
	}

	public java.lang.Boolean getIsAccountLocked() {
		return get("isAccountLocked");
	}

	public void setIsCredentialsExpired(java.lang.Boolean isCredentialsExpired) {
		set("isCredentialsExpired", isCredentialsExpired);
	}

	public java.lang.Boolean getIsCredentialsExpired() {
		return get("isCredentialsExpired");
	}

	public void setLockedDate(java.util.Date lockedDate) {
		set("lockedDate", lockedDate);
	}

	public java.util.Date getLockedDate() {
		return get("lockedDate");
	}

	public void setLoginDate(java.util.Date loginDate) {
		set("loginDate", loginDate);
	}

	public java.util.Date getLoginDate() {
		return get("loginDate");
	}

	public void setLoginFailureCount(java.lang.Integer loginFailureCount) {
		set("loginFailureCount", loginFailureCount);
	}

	public java.lang.Integer getLoginFailureCount() {
		return get("loginFailureCount");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("loginIp", loginIp);
	}

	public java.lang.String getLoginIp() {
		return get("loginIp");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

}
