package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaymentconfig<M extends BasePaymentconfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public void setConfigObjectStore(java.lang.String configObjectStore) {
		set("configObjectStore", configObjectStore);
	}

	public java.lang.String getConfigObjectStore() {
		return get("configObjectStore");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("orderList", orderList);
	}

	public java.lang.Integer getOrderList() {
		return get("orderList");
	}

	public void setPaymentConfigType(java.lang.Integer paymentConfigType) {
		set("paymentConfigType", paymentConfigType);
	}

	public java.lang.Integer getPaymentConfigType() {
		return get("paymentConfigType");
	}

	public void setPaymentFee(java.math.BigDecimal paymentFee) {
		set("paymentFee", paymentFee);
	}

	public java.math.BigDecimal getPaymentFee() {
		return get("paymentFee");
	}

	public void setPaymentFeeType(java.lang.Integer paymentFeeType) {
		set("paymentFeeType", paymentFeeType);
	}

	public java.lang.Integer getPaymentFeeType() {
		return get("paymentFeeType");
	}

}
