package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleResource<M extends BaseRoleResource<M>> extends Model<M> implements IBean {

	public void setRolesetId(java.lang.String rolesetId) {
		set("roleSet_id", rolesetId);
	}

	public java.lang.String getRolesetId() {
		return get("roleSet_id");
	}

	public void setResourcesetId(java.lang.String resourcesetId) {
		set("resourceSet_id", resourcesetId);
	}

	public java.lang.String getResourcesetId() {
		return get("resourceSet_id");
	}

}
