package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberattribute<M extends BaseMemberattribute<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public void setAttributeOptionStore(java.lang.String attributeOptionStore) {
		set("attributeOptionStore", attributeOptionStore);
	}

	public java.lang.String getAttributeOptionStore() {
		return get("attributeOptionStore");
	}

	public void setAttributeType(java.lang.Integer attributeType) {
		set("attributeType", attributeType);
	}

	public java.lang.Integer getAttributeType() {
		return get("attributeType");
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		set("isEnabled", isEnabled);
	}

	public java.lang.Boolean getIsEnabled() {
		return get("isEnabled");
	}

	public void setIsRequired(java.lang.Boolean isRequired) {
		set("isRequired", isRequired);
	}

	public java.lang.Boolean getIsRequired() {
		return get("isRequired");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("orderList", orderList);
	}

	public java.lang.Integer getOrderList() {
		return get("orderList");
	}

}
