package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("agreement", "id", Agreement.class);
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("articlecategory", "id", Articlecategory.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("deliverycorp", "id", Deliverycorp.class);
		arp.addMapping("deliverytype", "id", Deliverytype.class);
		arp.addMapping("footer", "id", Footer.class);
		arp.addMapping("friendlink", "id", Friendlink.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("logconfig", "id", Logconfig.class);
		arp.addMapping("memberattribute", "id", Memberattribute.class);
		arp.addMapping("memberrank", "id", Memberrank.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("module", "id", Module.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("paymentconfig", "id", Paymentconfig.class);
		arp.addMapping("post", "id", Post.class);
		arp.addMapping("productcategory", "id", Productcategory.class);
		arp.addMapping("producttype", "id", Producttype.class);
		arp.addMapping("reply", "id", Reply.class);
		arp.addMapping("resource", "id", Resource.class);
		arp.addMapping("role", "id", Role.class);
		// Composite Primary Key order: resourceSet_id,roleSet_id
		arp.addMapping("role_resource", "resourceSet_id,roleSet_id", RoleResource.class);
		arp.addMapping("testgroup", "id", Testgroup.class);
		arp.addMapping("teststudent", "id", Teststudent.class);
		arp.addMapping("topic", "id", Topic.class);
		arp.addMapping("user", "id", User.class);
	}
}

