package model;

import model.base.BaseAgreement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agreement extends BaseAgreement<Agreement> {
	public static final Agreement dao = new Agreement();
}
