package model;

import model.base.BaseArticlecategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Articlecategory extends BaseArticlecategory<Articlecategory> {
	public static final Articlecategory dao = new Articlecategory();
}
