package model;

import model.base.BaseDeliverytype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deliverytype extends BaseDeliverytype<Deliverytype> {
	public static final Deliverytype dao = new Deliverytype();
}
