package model;

import model.base.BaseDeliverycorp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deliverycorp extends BaseDeliverycorp<Deliverycorp> {
	public static final Deliverycorp dao = new Deliverycorp();
}
