package model;

import model.base.BaseFooter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Footer extends BaseFooter<Footer> {
	public static final Footer dao = new Footer();
}
