package model;

import model.base.BaseFriendlink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Friendlink extends BaseFriendlink<Friendlink> {
	public static final Friendlink dao = new Friendlink();
}
