package model;

import model.base.BaseLogconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logconfig extends BaseLogconfig<Logconfig> {
	public static final Logconfig dao = new Logconfig();
}
