package model;

import model.base.BaseMemberattribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberattribute extends BaseMemberattribute<Memberattribute> {
	public static final Memberattribute dao = new Memberattribute();
}
