package model;

import model.base.BaseMemberrank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberrank extends BaseMemberrank<Memberrank> {
	public static final Memberrank dao = new Memberrank();
}
