package model;

import model.base.BasePaymentconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paymentconfig extends BasePaymentconfig<Paymentconfig> {
	public static final Paymentconfig dao = new Paymentconfig();
}
