package model;

import model.base.BaseProductcategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Productcategory extends BaseProductcategory<Productcategory> {
	public static final Productcategory dao = new Productcategory();
}
