package model;

import model.base.BaseProducttype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Producttype extends BaseProducttype<Producttype> {
	public static final Producttype dao = new Producttype();
}
