package model;

import model.base.BaseTestgroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Testgroup extends BaseTestgroup<Testgroup> {
	public static final Testgroup dao = new Testgroup();
}
